

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Main Service (Runs all Node apps via 'npm run dev' using Concurrently)
  app:
    build: .
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    ports:
      - "3000:3000" # Frontend
      - "3001:3001" # Backend
      - "3002:3002" # Execution
      - "3003:3003" # Events
    environment:
      - DATABASE_URL=file:/app/packages/database/prisma/dev.db
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    depends_on:
      - redis
    command: npm run dev

volumes:
  redis_data:
  pg_data:
